library(readxl)
Insurance <- read_excel("C:/Users/srgra/Downloads/CarInsurances.xlsx")
View(Insurance)
dim(Insurance)
first.eight.rows = head(Insurance, 8)
print(first.eight.rows)
last.five.rows = tail(Insurance, 5)
print(last.five.rows)
ls()
objects()
help(summary)
summary(Insurance)